/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Arbol01 = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Arbol01.glb");

  const arbolTexture = useTexture("./textures/vegetation/Arbol02_.jpg");
  arbolTexture.flipY = false;
  arbolTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const arbolApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: arbolTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [arbolTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temp_meshply897.geometry}
        // material={materials["Material_0.010"]}
        material={arbolApt}
        position={[84.006, 31.005, -128.434]}
        rotation={[0, 0.021, 0]}
        scale={2.375}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Arbol01.glb");

export default Arbol01;
