/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Arbol02 = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Arbol02.glb");

  const arbolTexture = useTexture("./textures/vegetation/Arbol06_.jpg");
  arbolTexture.flipY = false;
  arbolTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const arbolApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: arbolTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [arbolTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temp_meshply915.geometry}
        // material={materials["Material_0.011"]}
        material={arbolApt}
        position={[98.123, 22.104, -53.184]}
        rotation={[-Math.PI, 0.251, -Math.PI]}
        scale={2.382}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Arbol02.glb");

export default Arbol02;
