/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Arbustos01 = (props) => {
  const { nodes, materials } = useGLTF("/models//Model02/Arbustos01.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temp_meshply933.geometry}
        material={materials["Material_0.013"]}
        position={[74.558, 22.836, -62.711]}
        rotation={[Math.PI, -1.518, Math.PI]}
        scale={2.458}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Arbustos01.glb");

export default Arbustos01;
