/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Ivy03 = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Ivy03_Web.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy03002.geometry}
        material={materials["*100.017"]}
        position={[116.655, 41.977, -75.723]}
        rotation={[Math.PI, -1.516, Math.PI]}
        scale={[1, 0.464, 1]}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Ivy03_Web.glb");

export default Ivy03;
