/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Palmera01 = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Palmera01.glb");

  const palmeraTexture = useTexture("./textures/vegetation/Palmera11_.jpg");
  palmeraTexture.flipY = false;
  palmeraTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const palmeraApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: palmeraTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [palmeraTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temp_meshply769.geometry}
        // material={materials["Material_0.019"]}
        material={palmeraApt}
        position={[139.949, 28.745, -83.606]}
        rotation={[0, 0.744, 0]}
        scale={3.569}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Palmera01.glb");

export default Palmera01;
