/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Palmera02 = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Palmera02.glb");

  const palmeraTexture = useTexture("./textures/vegetation/Palmera05_.jpg");
  palmeraTexture.flipY = false;
  palmeraTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const palmeraApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: palmeraTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [palmeraTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temp_meshply819.geometry}
        // material={materials["Material_0.017"]}
        material={palmeraApt}
        position={[144.952, 28.923, -90.146]}
        rotation={[Math.PI, -0.395, Math.PI]}
        scale={3.878}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Palmera02.glb");

export default Palmera02;
