/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Palmera04 = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Palmera04.glb");

  const palmeraTexture = useTexture("./textures/vegetation/Palmera02_.jpg");
  palmeraTexture.flipY = false;
  palmeraTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const palmeraApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: palmeraTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [palmeraTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temp_meshply842.geometry}
        // material={materials["Material_0.006"]}
        material={palmeraApt}
        position={[127.818, 29.287, -94.615]}
        rotation={[0, 0.009, 0]}
        scale={4.565}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Palmera04.glb");

export default Palmera04;
