/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Palmera03 = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Palmera03.glb");

  const palmeraTexture = useTexture("./textures/vegetation/Palmera04_.jpg");
  palmeraTexture.flipY = false;
  palmeraTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const palmeraApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: palmeraTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [palmeraTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temp_meshply831.geometry}
        // material={materials["Material_0.015"]}
        material={palmeraApt}
        position={[56.983, 24.397, -63.635]}
        rotation={[0, -0.131, 0]}
        scale={3.736}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Palmera03.glb");

export default Palmera03;
