/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Acero = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Acero_Web.glb");

  const aceroTexture = useTexture("./textures/V02/Acero.jpg");
  aceroTexture.flipY = false;
  aceroTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const aceroApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: aceroTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [aceroTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Acero_Web.geometry}
        // material={nodes.Acero_Web.material}
        material={aceroApt}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Acero_Web.glb");

export default Acero;
