/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Agua = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Agua_Web.glb");

  const aguaTexture = useTexture("./textures/V02/Agua.jpg");
  aguaTexture.flipY = false;
  aguaTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const aguaApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: aguaTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [aguaTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Agua_Web.geometry}
        // material={nodes.Agua_Web.material}
        material={aguaApt}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Agua_Web.glb");

export default Agua;
