/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Apartments = (props) => {
  const { nodes, materials } = useGLTF("/models/AUA_Model.glb");

  const aceroTexture = useTexture("./textures/Apt_Acero.jpg");
  aceroTexture.flipY = false;
  aceroTexture.colorSpace = THREE.SRGBColorSpace;

  const aguaTexture = useTexture("./textures/Apt_Agua.jpg");
  aguaTexture.flipY = false;
  aguaTexture.colorSpace = THREE.SRGBColorSpace;

  const concretoTexture = useTexture("./textures/Apt_Concreto.jpg");
  concretoTexture.flipY = false;
  concretoTexture.colorSpace = THREE.SRGBColorSpace;

  const losasTexture = useTexture("./textures/Apt_Losas.jpg");
  losasTexture.flipY = false;
  losasTexture.colorSpace = THREE.SRGBColorSpace;

  const maderaTexture = useTexture("./textures/Apt_Madera.jpg");
  maderaTexture.flipY = false;
  maderaTexture.colorSpace = THREE.SRGBColorSpace;

  const murosTexture = useTexture("./textures/Apt_Muros.jpg");
  murosTexture.flipY = false;
  murosTexture.colorSpace = THREE.SRGBColorSpace;

  const piedraTexture = useTexture("./textures/Apt_Piedra.jpg");
  piedraTexture.flipY = false;
  piedraTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const aceroApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: aceroTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [aceroTexture]);

  // Agua
  const aguaApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: aguaTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [aguaTexture]);

  // Concreto
  const concretoApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: concretoTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [concretoTexture]);

  // Losas
  const losasApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: losasTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [losasTexture]);

  // Madera
  const maderaApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: maderaTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [maderaTexture]);

  // Muros
  const murosApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: murosTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [murosTexture]);

  // Piedra
  const piedraApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: piedraTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [piedraTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Muros_Piedra.geometry}
        // material={materials.Wood}
        material={murosApt}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Piedra.geometry}
        // material={materials.Landscape}
        material={piedraApt}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Acero.geometry}
        // material={materials['Brushed black metal brass']}
        material={aceroApt}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Agua.geometry}
        // material={materials.Agua}
        material={aguaApt}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Losas.geometry}
        // material={materials.Wall}
        material={losasApt}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Concreto.geometry}
        // material={materials.Wall}
        material={concretoApt}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Madera.geometry}
        // material={materials.Wood}
        material={maderaApt}
      />
    </group>
  );
};

useGLTF.preload("/models/AUA_Model.glb");

export default Apartments;
