/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Concreto = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Concreto_Web.glb");

  const concretoTexture = useTexture("./textures/V02/Concreto.jpg");
  concretoTexture.flipY = false;
  concretoTexture.colorSpace = THREE.SRGBColorSpace;

  // Concreto
  const concretoApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: concretoTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [concretoTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Concreto_Web.geometry}
        // material={nodes.Concreto_Web.material}
        material={concretoApt}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Concreto_Web.glb");

export default Concreto;
