/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Fur_Tex = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Fur_Tex_Web.glb");

  const fur_Tex_Texture = useTexture("./textures/V02/Fur_Tex.jpg");
  fur_Tex_Texture.flipY = false;
  fur_Tex_Texture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const fur_Tex_Apt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: fur_Tex_Texture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [fur_Tex_Texture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fur_Tex_Web02.geometry}
        // material={nodes.Fur_Tex_Web02.material}
        material={fur_Tex_Apt}
        position={[108.045, 42.033, -65.715]}
        rotation={[0, -1.343, Math.PI]}
        scale={-1}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Fur_Tex_Web.glb");

export default Fur_Tex;
