/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Fur_Wood = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Fur_Wood_Web.glb");

  const fur_Wood_Texture = useTexture("./textures/V02/Fur_Wood.jpg");
  fur_Wood_Texture.flipY = false;
  fur_Wood_Texture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const fur_Wood_Apt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: fur_Wood_Texture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [fur_Wood_Texture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fur_Wood_Web02.geometry}
        // material={nodes.Fur_Wood_Web02.material}
        material={fur_Wood_Apt}
        position={[135.9, 26.82, -54.624]}
        rotation={[0, -1.363, 0]}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Fur_Wood_Web.glb");

export default Fur_Wood;
