/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Gravel = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Gravel_Web.glb");

  const gravelTexture = useTexture("./textures/V02/Piedra.jpg");
  gravelTexture.flipY = false;
  gravelTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const gravelApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: gravelTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [gravelTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Gravel_Web.geometry}
        // material={nodes.Gravel_Web.material}
        material={gravelApt}
        position={[0, 0.05, 0]}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Gravel_Web.glb");

export default Gravel;
