/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Losas = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Losas_Web.glb");

  const losasTexture = useTexture("./textures/V02/Losas.jpg");
  losasTexture.flipY = false;
  losasTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const losasApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: losasTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [losasTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Losas_Web.geometry}
        // material={nodes.Losas_Web.material}
        material={losasApt}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Losas_Web.glb");

export default Losas;
