/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Madera = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Madera_Web.glb");

  const maderaTexture = useTexture("./textures/V02/Madera.jpg");
  maderaTexture.flipY = false;
  maderaTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const maderaApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: maderaTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [maderaTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Madera_Web.geometry}
        // material={nodes.Madera_Web.material}
        material={maderaApt}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Madera_Web.glb");

export default Madera;
