/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Muros = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Muros_Piedra_Web.glb");

  const murosTexture = useTexture("./textures/V02/Muros.jpg");
  murosTexture.flipY = false;
  murosTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const murosApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: murosTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [murosTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Muros_Piedra_Web.geometry}
        // material={nodes.Muros_Piedra_Web.material}
        material={murosApt}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Muros_Piedra_Web.glb");

export default Muros;
