/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Pavement = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Pavement_Web.glb");

  const pavementTexture = useTexture("./textures/V02/Pavement.jpg");
  pavementTexture.flipY = false;
  pavementTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const pavementApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: pavementTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [pavementTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pavement_Web.geometry}
        // material={nodes.Pavement_Web.material}
        material={pavementApt}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Pavement_Web.glb");

export default Pavement;
