/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useMemo, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { annotation3d, residenceTogglesAtom } from "../UI";
import { useAtom } from "jotai";

export const tipologiasResidencias = [
  "2BR_G_A",
  "2BR_G_B",
  "2BR_N1_A",
  "2BR_N1_B",
  "2BR_N2_A",
  "2BR_N2_B",
  "3BR_G_A",
  "3BR_G_B",
  "3BR_N1_A",
  "3BR_N1_B",
  "3BR_N2_A",
  "3BR_N2_B",
  "4BR_A",
  "4BR_B",
];

const Residences = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Residential_Areas.glb");

  const [annotation] = useAtom(annotation3d);
  const [residenceToggles] = useAtom(residenceTogglesAtom);

  //State for hover scaling
  const [hoveredMesh, setHoveredMesh] = useState(null);

  //Refs for each mesh
  const meshRefs = useRef({});

  //Refs for materials to handle opacity
  const materialRefs = useRef({});

  //Effect to handle opacity and color changes
  useEffect(() => {
    Object.keys(materialRefs.current).forEach((meshName) => {
      const material = materialRefs.current[meshName];
      if (material) {
        if (hoveredMesh === meshName) {
          material.opacity = 0.8;
          // material.emissive.set(0xffffff) // White emissive for bright white effect
          material.emissive.copy(material.originalEmissive);
          material.emissiveIntensity = 0.3;
          material.needsUpdate = true;
        } else {
          material.opacity = 0.45; // Restaurar la transparencia base de 0.75
          material.emissive.copy(material.originalEmissive); // Restore original emissive
          material.emissiveIntensity = 0;
          material.needsUpdate = true;
        }
        material.transparent = true;
      }
    });
  }, [hoveredMesh]);

  const handlePointerEnter = (meshName, event) => {
    event.stopPropagation?.();

    setHoveredMesh(meshName);
    document.body.style.cursor = "pointer";
  };

  // const handlePointerOut = () => {

  const handlePointerLeave = (event) => {
    event.stopPropagation?.();

    setHoveredMesh(null);
    document.body.style.cursor = "default";
  };

  // Mapping de objetos a imagenes y titulos
  const objectMappings = {
    N1_G_A1: {
      image: "./FP/G_A.png",
      title: "L01 A1 PENT GARDEN",
    },
    N1_G_A2: {
      image: "./FP/G_A.png",
      title: "L01 A2 PENT GARDEN",
    },
    N1_G_B: {
      image: "./FP/G_B.png",
      title: "L01 B PENT GARDEN",
    },
    N2_A1: {
      image: "./FP/Apt_A.png",
      title: "L02 A1 RESIDENCE",
    },
    N2_A2: {
      image: "./FP/Apt_A.png",
      title: "L02 A2 RESIDENCE",
    },
    N2_B: {
      image: "./FP/Apt_B.png",
      title: "L02 B RESIDENCE",
    },
    N3_A1: {
      image: "./FP/Apt_A.png",
      title: "L03 A1 RESIDENCE",
    },
    N3_A2: {
      image: "./FP/Apt_A.png",
      title: "L03 A2 RESIDENCE",
    },
    N3_B: {
      image: "./FP/Apt_B.png",
      title: "L03 B RESIDENCE",
    },
    N4_A1: {
      image: "./FP/PH_A.png",
      title: "L04 A1 PENTHOUSE",
    },
    N4_A2: {
      image: "./FP/PH_A.png",
      title: "L04 A2 PENTHOUSE",
    },
    N4_B: {
      image: "./FP/PH_B.png",
      title: "L04 B PENTHOUSE",
    },
  };

  // Handle click to active amenities camera
  // const handleClick = (objectName) => {
  const handleClick = (objectName, event) => {
    event?.stopPropagation?.();
    // setCameraMode(CameraModes.RESIDENCES)

    // Disparar evento para mostrar floating panel con informacion especifica del objeto
    const mapping = objectMappings[objectName];
    if (mapping) {
      // window.dispatchEvent(new CustomEvent('annotation-click', {
      window.dispatchEvent(
        new CustomEvent("mesh-click", {
          detail: {
            image: mapping.image,
            annotation: mapping.title,
            meshName: objectName,
            // meshName: objectName,
            // source: 'mesh'
          },
        }),
      );
    }
  };

  // Clone material to handle opacity and allow optional color override per mesh
  const getMaterial = (baseMaterial, meshName, colorOverride) => {
    if (!materialRefs.current[meshName]) {
      const clonedMaterial = baseMaterial.clone();
      clonedMaterial.transparent = true;

      clonedMaterial.depthWrite = true; // keep depth buffer for proper occlusion
      clonedMaterial.depthTest = true;

      clonedMaterial.opacity = 0.75; // Establecer transparencia de 0.75
      clonedMaterial.originalColor = clonedMaterial.color.clone(); // Store original color
      clonedMaterial.originalEmissive = clonedMaterial.emissive.clone(); //Store original emissive

      // Optional: override base color from the mesh config
      if (colorOverride) {
        clonedMaterial.color.set(colorOverride);
      }

      materialRefs.current[meshName] = clonedMaterial;
    }
    return materialRefs.current[meshName];
  };

  const tipoCheck = (tipologia, residenceType) => {
    if (annotation === "residences") {
      if (residenceType && residenceToggles[residenceType]) {
        return true;
      }
      return false;
    }
    return false;
  };

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Areas.geometry}
        // material={nodes.Residential_Areas.material}

        ref={(el) => (meshRefs.current["N4_A2"] = el)}
        // geometry={nodes.R_2BR_G_F.geometry}
        material={getMaterial(
          nodes.Residential_Areas.material,
          "N4_A2",
          "#2F4F5A",
        )}
        visible={tipoCheck("N4_A2", "Apt A Penthouse")}
        scale={hoveredMesh === "N4_A2" ? 1.003 : 1}
        // onPointerOver={() => handlePointerOver('N4_A2')}
        // onPointerOut={handlePointerOut}

        onPointerEnter={(event) => handlePointerEnter("N4_A2", event)}
        onPointerLeave={handlePointerLeave}
        onClick={(event) => handleClick("N4_A2", event)}
      >
        <lineSegments scale={1.001} raycast={() => null}>
          <edgesGeometry
            args={[nodes.Residential_Areas.geometry, Math.PI * 2]}
          />
          <lineBasicMaterial color="#C3C3C3" transparent opacity={0.9} />
        </lineSegments>
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Areas001.geometry}
        // material={nodes.Residential_Areas001.material}

        ref={(el) => (meshRefs.current["N4_B"] = el)}
        material={getMaterial(
          nodes.Residential_Areas001.material,
          "N4_B",
          "#2F4F5A",
        )}
        visible={tipoCheck("N4_B", "Apt B Penthouse")}
        scale={hoveredMesh === "N4_B" ? 1.003 : 1}
        // onPointerOver={() => handlePointerOver('N4_B')}
        // onPointerOut={handlePointerOut}

        onPointerEnter={(event) => handlePointerEnter("N4_B", event)}
        onPointerLeave={handlePointerLeave}
        onClick={(event) => handleClick("N4_B", event)}
      >
        <lineSegments scale={1.001} raycast={() => null}>
          <edgesGeometry
            args={[nodes.Residential_Areas001.geometry, Math.PI * 2]}
          />
          <lineBasicMaterial color="#C3C3C3" transparent opacity={0.9} />
        </lineSegments>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Areas002.geometry}
        // material={nodes.Residential_Areas002.material}

        ref={(el) => (meshRefs.current["N4_A1"] = el)}
        material={getMaterial(
          nodes.Residential_Areas002.material,
          "N4_A1",
          "#2F4F5A",
        )}
        visible={tipoCheck("N4_A1", "Apt A Penthouse")}
        scale={hoveredMesh === "N4_A1" ? 1.003 : 1}
        // onPointerOver={() => handlePointerOver('N4_A1')}
        // onPointerOut={handlePointerOut}

        onPointerEnter={(event) => handlePointerEnter("N4_A1", event)}
        onPointerLeave={handlePointerLeave}
        onClick={(event) => handleClick("N4_A1", event)}
      >
        <lineSegments scale={1.001} raycast={() => null}>
          <edgesGeometry
            args={[nodes.Residential_Areas002.geometry, Math.PI * 2]}
          />
          <lineBasicMaterial color="#C3C3C3" transparent opacity={0.9} />
        </lineSegments>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Areas003.geometry}
        // material={nodes.Residential_Areas003.material}

        ref={(el) => (meshRefs.current["N3_A2"] = el)}
        material={getMaterial(
          nodes.Residential_Areas003.material,
          "N3_A2",
          "#2F4F5A",
        )}
        visible={tipoCheck("N3_A2", "Apt A")}
        scale={hoveredMesh === "N3_A2" ? 1.003 : 1}
        // onPointerOver={() => handlePointerOver('N3_A2')}
        // onPointerOut={handlePointerOut}

        onPointerEnter={(event) => handlePointerEnter("N3_A2", event)}
        onPointerLeave={handlePointerLeave}
        onClick={(event) => handleClick("N3_A2", event)}
      >
        <lineSegments scale={1.001} raycast={() => null}>
          <edgesGeometry
            args={[nodes.Residential_Areas003.geometry, Math.PI * 2]}
          />
          <lineBasicMaterial color="#C3C3C3" transparent opacity={0.9} />
        </lineSegments>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Areas004.geometry}
        // material={nodes.Residential_Areas004.material}

        ref={(el) => (meshRefs.current["N3_B"] = el)}
        material={getMaterial(
          nodes.Residential_Areas004.material,
          "N3_B",
          "#2F4F5A",
        )}
        visible={tipoCheck("N3_B", "Apt B")}
        scale={hoveredMesh === "N3_B" ? 1.003 : 1}
        // onPointerOver={() => handlePointerOver('N3_B')}
        // onPointerOut={handlePointerOut}

        onPointerEnter={(event) => handlePointerEnter("N3_B", event)}
        onPointerLeave={handlePointerLeave}
        onClick={(event) => handleClick("N3_B", event)}
      >
        <lineSegments scale={1.001} raycast={() => null}>
          <edgesGeometry
            args={[nodes.Residential_Areas004.geometry, Math.PI * 2]}
          />
          <lineBasicMaterial color="#C3C3C3" transparent opacity={0.9} />
        </lineSegments>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Areas005.geometry}
        // material={nodes.Residential_Areas005.material}

        ref={(el) => (meshRefs.current["N3_A1"] = el)}
        material={getMaterial(
          nodes.Residential_Areas005.material,
          "N3_A1",
          "#2F4F5A",
        )}
        visible={tipoCheck("N3_A1", "Apt A")}
        scale={hoveredMesh === "N3_A1" ? 1.003 : 1}
        // onPointerOver={() => handlePointerOver('N3_A1')}
        // onPointerOut={handlePointerOut}

        onPointerEnter={(event) => handlePointerEnter("N3_A1", event)}
        onPointerLeave={handlePointerLeave}
        onClick={(event) => handleClick("N3_A1", event)}
      >
        <lineSegments scale={1.001} raycast={() => null}>
          <edgesGeometry
            args={[nodes.Residential_Areas005.geometry, Math.PI * 2]}
          />
          <lineBasicMaterial color="#C3C3C3" transparent opacity={0.9} />
        </lineSegments>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Areas006.geometry}
        // material={nodes.Residential_Areas006.material}

        ref={(el) => (meshRefs.current["N2_A2"] = el)}
        material={getMaterial(
          nodes.Residential_Areas006.material,
          "N2_A2",
          "#2F4F5A",
        )}
        visible={tipoCheck("N2_A2", "Apt A")}
        scale={hoveredMesh === "N2_A2" ? 1.003 : 1}
        // onPointerOver={() => handlePointerOver('N2_A2')}
        // onPointerOut={handlePointerOut}

        onPointerEnter={(event) => handlePointerEnter("N2_A2", event)}
        onPointerLeave={handlePointerLeave}
        onClick={(event) => handleClick("N2_A2", event)}
      >
        <lineSegments scale={1.001} raycast={() => null}>
          <edgesGeometry
            args={[nodes.Residential_Areas006.geometry, Math.PI * 2]}
          />
          <lineBasicMaterial color="#C3C3C3" transparent opacity={0.9} />
        </lineSegments>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Areas007.geometry}
        // material={nodes.Residential_Areas007.material}

        ref={(el) => (meshRefs.current["N2_B"] = el)}
        material={getMaterial(
          nodes.Residential_Areas007.material,
          "N2_B",
          "#2F4F5A",
        )}
        visible={tipoCheck("N2_B", "Apt B")}
        scale={hoveredMesh === "N2_B" ? 1.003 : 1}
        // onPointerOver={() => handlePointerOver('N2_B')}
        // onPointerOut={handlePointerOut}

        onPointerEnter={(event) => handlePointerEnter("N2_B", event)}
        onPointerLeave={handlePointerLeave}
        onClick={(event) => handleClick("N2_B", event)}
      >
        <lineSegments scale={1.001} raycast={() => null}>
          <edgesGeometry
            args={[nodes.Residential_Areas007.geometry, Math.PI * 2]}
          />
          <lineBasicMaterial color="#C3C3C3" transparent opacity={0.9} />
        </lineSegments>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Areas008.geometry}
        // material={nodes.Residential_Areas008.material}

        ref={(el) => (meshRefs.current["N2_A1"] = el)}
        material={getMaterial(
          nodes.Residential_Areas008.material,
          "N2_A1",
          "#2F4F5A",
        )}
        visible={tipoCheck("N2_A1", "Apt A")}
        scale={hoveredMesh === "N2_A1" ? 1.003 : 1}
        // onPointerOver={() => handlePointerOver('N2_A1')}
        // onPointerOut={handlePointerOut}

        onPointerEnter={(event) => handlePointerEnter("N2_A1", event)}
        onPointerLeave={handlePointerLeave}
        onClick={(event) => handleClick("N2_A1", event)}
      >
        <lineSegments scale={1.001} raycast={() => null}>
          <edgesGeometry
            args={[nodes.Residential_Areas008.geometry, Math.PI * 2]}
          />
          <lineBasicMaterial color="#C3C3C3" transparent opacity={0.9} />
        </lineSegments>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Areas009.geometry}
        // material={nodes.Residential_Areas009.material}

        ref={(el) => (meshRefs.current["N1_G_A2"] = el)}
        material={getMaterial(
          nodes.Residential_Areas009.material,
          "N1_G_A2",
          "#2F4F5A",
        )}
        visible={tipoCheck("N1_G_A2", "Apt A Garden")}
        scale={hoveredMesh === "N1_G_A2" ? 1.003 : 1}
        // onPointerOver={() => handlePointerOver('N1_G_A2')}
        // onPointerOut={handlePointerOut}

        onPointerEnter={(event) => handlePointerEnter("N1_G_A2", event)}
        onPointerLeave={handlePointerLeave}
        onClick={(event) => handleClick("N1_G_A2", event)}
      >
        <lineSegments scale={1.001} raycast={() => null}>
          <edgesGeometry
            args={[nodes.Residential_Areas009.geometry, Math.PI * 2]}
          />
          <lineBasicMaterial color="#C3C3C3" transparent opacity={0.9} />
        </lineSegments>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Areas010.geometry}
        // material={nodes.Residential_Areas010.material}

        ref={(el) => (meshRefs.current["N1_G_B"] = el)}
        material={getMaterial(
          nodes.Residential_Areas010.material,
          "N1_G_B",
          "#2F4F5A",
        )}
        visible={tipoCheck("N1_G_B", "Apt B Garden")}
        scale={hoveredMesh === "N1_G_B" ? 1.003 : 1}
        // onPointerOver={() => handlePointerOver('N1_G_B')}
        // onPointerOut={handlePointerOut}

        onPointerEnter={(event) => handlePointerEnter("N1_G_B", event)}
        onPointerLeave={handlePointerLeave}
        onClick={(event) => handleClick("N1_G_B", event)}
      >
        <lineSegments scale={1.001} raycast={() => null}>
          <edgesGeometry
            args={[nodes.Residential_Areas010.geometry, Math.PI * 2]}
          />
          <lineBasicMaterial color="#C3C3C3" transparent opacity={0.9} />
        </lineSegments>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Areas011.geometry}
        // material={nodes.Residential_Areas011.material}

        ref={(el) => (meshRefs.current["N1_G_A1"] = el)}
        material={getMaterial(
          nodes.Residential_Areas011.material,
          "N1_G_A1",
          "#2F4F5A",
        )}
        visible={tipoCheck("N1_G_A1", "Apt A Garden")}
        scale={hoveredMesh === "N1_G_A1" ? 1.003 : 1}
        // onPointerOver={() => handlePointerOver('N1_G_A1')}
        // onPointerOut={handlePointerOut}

        onPointerEnter={(event) => handlePointerEnter("N1_G_A1", event)}
        onPointerLeave={handlePointerLeave}
        onClick={(event) => handleClick("N1_G_A1", event)}
      >
        <lineSegments scale={1.001} raycast={() => null}>
          <edgesGeometry
            args={[nodes.Residential_Areas011.geometry, Math.PI * 2]}
          />
          <lineBasicMaterial color="#C3C3C3" transparent opacity={0.9} />
        </lineSegments>
      </mesh>
    </group>
  );
};

useGLTF.preload("/models/Model02/Residential_Areas.glb");

export default Residences;
