/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Sand = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Sand_Web.glb");

  const sandTexture = useTexture("./textures/V02/Sand.jpg");
  sandTexture.flipY = false;
  sandTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const sandApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: sandTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [sandTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sand_Web.geometry}
        // material={nodes.Sand_Web.material}
        material={sandApt}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Sand_Web.glb");

export default Sand;
