/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Topo = (props) => {
  const { nodes, materials } = useGLTF("/models/AUA_Topo.glb");

  const tex = useTexture({
    map: "textures/ground/diffuse_Topo.jpg",
    normalMap: "textures/ground/normal_Topo.jpg",
    roughnessMap: "textures/ground/rough_Topo.jpg",
    aoMap: "textures/ground/AO_Topo.jpg",
    displacementMap: "textures/ground/diss_Topo.jpg",
  });

  tex.map.wrapS = tex.map.wrapT = THREE.RepeatWrapping;
  tex.normalMap.wrapS = tex.normalMap.wrapT = THREE.RepeatWrapping;
  tex.roughnessMap.wrapS = tex.roughnessMap.wrapT = THREE.RepeatWrapping;
  tex.aoMap.wrapS = tex.aoMap.wrapT = THREE.RepeatWrapping;
  tex.displacementMap.wrapS = tex.displacementMap.wrapT = THREE.RepeatWrapping;

  tex.map.repeat.set(16, 16); // si repites el resto también
  tex.normalMap.repeat.set(16, 16); // si repites el resto también
  tex.roughnessMap.repeat.set(16, 16); // si repites el resto también
  tex.aoMap.repeat.set(16, 16); // si repites el resto también
  tex.displacementMap.repeat.set(16, 16); // si repites el resto también

  // displacementMap normalmente NO lleva SRGB
  tex.map.colorSpace = THREE.SRGBColorSpace;
  tex.normalMap.colorSpace = THREE.SRGBColorSpace;
  tex.roughnessMap.colorSpace = THREE.SRGBColorSpace;
  tex.aoMap.colorSpace = THREE.SRGBColorSpace;
  tex.displacementMap.colorSpace = THREE.SRGBColorSpace;

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Topo.geometry}
        // material={nodes.Topo.material}
      >
        <meshStandardMaterial
          {...tex}
          displacementScale={0.6} // ajusta esto
          displacementBias={0.0} // opcional
          toneMapped={false}
        />
      </mesh>
    </group>
  );
};

useGLTF.preload("/models/AUA_Topo.glb");

export default Topo;
