/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Topo02 = (props) => {
  const { nodes, materials } = useGLTF("/models/Model02/Topo_Web.glb");

  const topoTexture = useTexture("./textures/V02/Topo.jpg");
  topoTexture.flipY = false;
  topoTexture.colorSpace = THREE.SRGBColorSpace;

  // Acero
  const topoApt = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: topoTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [topoTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Topo_Web02.geometry}
        // material={nodes.Topo_Web02.material}
        material={topoApt}
        position={[89.785, 0, -99.394]}
      />
    </group>
  );
};

useGLTF.preload("/models/Model02/Topo_Web.glb");

export default Topo02;
