/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Arbol06 = (props) => {
  const { nodes, materials } = useGLTF("/models/vegetation/Arbol06.glb");

  const arbol06Texture = useTexture("./textures/vegetation/Arbol06_.jpg");
  arbol06Texture.flipY = false;
  arbol06Texture.colorSpace = THREE.SRGBColorSpace;

  // Arbol02
  const arbol06Veg = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: arbol06Texture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [arbol06Texture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temp_meshply915.geometry}
        // material={materials["Material_0.011"]}
        material={arbol06Veg}
        position={[98.123, 22.104, -53.184]}
        rotation={[-Math.PI, 0.251, -Math.PI]}
        scale={2.382}
      />
    </group>
  );
};

useGLTF.preload("/models/vegetation/Arbol06.glb");

export default Arbol06;
