/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Arbol02 = (props) => {
  const { nodes, materials } = useGLTF("/models/vegetation/Arbol02.glb");

  const arbol02Texture = useTexture("./textures/vegetation/Arbol02_.jpg");
  arbol02Texture.flipY = false;
  arbol02Texture.colorSpace = THREE.SRGBColorSpace;

  // Arbol02
  const arbol02Veg = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: arbol02Texture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [arbol02Texture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temp_meshply897.geometry}
        // material={materials["Material_0.010"]}
        material={arbol02Veg}
        position={[84.006, 31.005, -128.434]}
        rotation={[0, 0.021, 0]}
        scale={2.375}
      />
    </group>
  );
};

useGLTF.preload("/models/vegetation/Arbol02.glb");

export default Arbol02;
