/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Arbustos01 = (props) => {
  const { nodes, materials } = useGLTF("/models/vegetation/Arbustos01.glb");

  // const arbustos01Texture = useTexture("./textures/vegetation/Apt_Acero.jpg");
  // arbustos01Texture.flipY = false;
  // arbustos01Texture.colorSpace = THREE.SRGBColorSpace;

  // // Arbol02
  // const arbustos01Veg = useMemo(() => {
  //   return new THREE.MeshStandardMaterial({
  //     map: arbustos01Texture,
  //     toneMapped: false, // prevent threejs from washing colors
  //   });
  // }, [arbustos01Texture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temp_meshply933.geometry}
        material={materials["Material_0.013"]}
        // material={arbustos01Veg}
        position={[74.558, 22.836, -62.711]}
        rotation={[Math.PI, -1.518, Math.PI]}
        scale={2.458}
      />
    </group>
  );
};

useGLTF.preload("/models/vegetation/Arbustos01.glb");

export default Arbustos01;
