/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Cactus01 = (props) => {
  const { nodes, materials } = useGLTF("/models/vegetation/Cactus01.glb");

  const cactus01Texture = useTexture("./textures/vegetation/Cactus01_.jpg");
  cactus01Texture.flipY = false;
  cactus01Texture.colorSpace = THREE.SRGBColorSpace;

  // Arbol02
  const cactus01Veg = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: cactus01Texture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [cactus01Texture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temp_meshply925.geometry}
        // material={materials["Material_0.012"]}
        material={cactus01Veg}
        position={[124.358, 23.024, -41.275]}
        rotation={[Math.PI, -0.859, Math.PI]}
        scale={1.132}
      />
    </group>
  );
};

useGLTF.preload("/models/vegetation/Cactus01.glb");

export default Cactus01;
