/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Palmera05 = (props) => {
  const { nodes, materials } = useGLTF("/models/vegetation/Palmera05.glb");

  const palmera05Texture = useTexture("./textures/vegetation/Palmera05_.jpg");
  palmera05Texture.flipY = false;
  palmera05Texture.colorSpace = THREE.SRGBColorSpace;

  // Arbol02
  const palmera05Veg = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: palmera05Texture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [palmera05Texture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temp_meshply819.geometry}
        // material={materials["Material_0.006"]}
        material={palmera05Veg}
        position={[144.952, 28.923, -90.146]}
        rotation={[Math.PI, -0.395, Math.PI]}
        scale={3.878}
      />
    </group>
  );
};

useGLTF.preload("/models/vegetation/Palmera05.glb");

export default Palmera05;
