/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Palmera02 = (props) => {
  const { nodes, materials } = useGLTF("/models/vegetation/Palmera02.glb");

  const palmera02Texture = useTexture("./textures/vegetation/Palmera02_.jpg");
  palmera02Texture.flipY = false;
  palmera02Texture.colorSpace = THREE.SRGBColorSpace;

  // Arbol02
  const palmera02Veg = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: palmera02Texture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [palmera02Texture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temp_meshply842.geometry}
        // material={materials["Material_0.008"]}
        material={palmera02Veg}
        position={[127.818, 29.287, -94.615]}
        rotation={[0, 0.009, 0]}
        scale={4.565}
      />
    </group>
  );
};

useGLTF.preload("/models/vegetation/Palmera02.glb");

export default Palmera02;
