/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Palmera04 = (props) => {
  const { nodes, materials } = useGLTF("/models/vegetation/Palmera04.glb");

  const palmera04Texture = useTexture("./textures/vegetation/Palmera04_.jpg");
  palmera04Texture.flipY = false;
  palmera04Texture.colorSpace = THREE.SRGBColorSpace;

  // Arbol02
  const palmera04Veg = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: palmera04Texture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [palmera04Texture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temp_meshply831.geometry}
        // material={materials["Material_0.007"]}
        material={palmera04Veg}
        position={[56.983, 24.397, -63.635]}
        rotation={[0, -0.131, 0]}
        scale={3.736}
      />
    </group>
  );
};

useGLTF.preload("/models/vegetation/Palmera04.glb");

export default Palmera04;
