/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Palmera11 = (props) => {
  const { nodes, materials } = useGLTF("/models/vegetation/Palmera11.glb");

  const palmera11Texture = useTexture("./textures/vegetation/Palmera11_.jpg");
  palmera11Texture.flipY = false;
  palmera11Texture.colorSpace = THREE.SRGBColorSpace;

  // Arbol02
  const palmera11Veg = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: palmera11Texture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [palmera11Texture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temp_meshply769.geometry}
        // material={materials["Material_0.004"]}
        material={palmera11Veg}
        position={[139.949, 28.745, -83.606]}
        rotation={[0, 0.744, 0]}
        scale={3.569}
      />
    </group>
  );
};

useGLTF.preload("/models/vegetation/Palmera11.glb");

export default Palmera11;
